# Automatic updated for the vulnerabilities databases, based on NVD
name: "vuln-db-update"

on:
  schedule:
    - cron: "59 23 */7 * *"
  workflow_dispatch:

jobs:
  update-db:
    name: "Check for CVE DB updates on NVD"
    runs-on: "ubuntu-latest"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: pull the branch
        run: |
          git pull --force
          git checkout --orphan "temp_branch"
  
      - name: run updateDB script
        run: ./updateDB.py

      - name: Commit changes
        run: |
          git config --global user.name "SixSq CI Bot"
          git config --global user.email "support@sixsq.com"
          git add -A
          git commit -m "Auto DB update from CI"

      - name: Move to main branch
        run: |
          git branch -D main
          git branch -m main
          git push -f --set-upstream origin main

  notify:
    if: failure()
    name: Post Workflow Status To Slack
    needs:
      - update-db
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          icon_emoji: ':rocket:'
